# Dependabot will run on day 16 of each month at 02:10 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "10 2 16 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "10 2 16 * *"
    open-pull-requests-limit: 20
    assignees:
      - "klein0r"
    versioning-strategy: "increase"
